<a href="https://colab.research.google.com/github/mahdibaghbanzadeh/NLP/blob/main/notebooks/Huggingface_Transformers_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Agenda:**

1.   What is Transfer Learning.
2.   Using Transformes model in Pytorch







**Resources:**
2.   https://www.notion.so/Transfer-Learning-Huggingface-Transformers-in-Pytorch-6e8f4c0b7dc34f13a01ec78a02aff9f5




In [1]:
!pip install transformers -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 49.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 22.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 105.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 72.4 MB/s eta 0:00:00


**BERT Embeding**

In [2]:
from transformers import DistilBertTokenizer, DistilBertModel
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained("distilbert-base-uncased")
text = "some text for model"
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
output

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.bias', 'vocab_projector.bias', 'vocab_layer_norm.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BaseModelOutput(last_hidden_state=tensor([[[-0.3349, -0.1658, -0.0110,  ..., -0.2789,  0.0950,  0.4630],
         [-0.0397, -0.0176, -0.3552,  ..., -0.2689,  0.1300,  0.5941],
         [-0.0757,  0.3424,  0.0660,  ..., -0.5298, -0.2513,  0.1726],
         [ 0.0395, -0.0122,  0.2089,  ..., -0.3721,  0.1763,  0.1254],
         [-0.2027, -0.2934, -0.1556,  ..., -0.5440, -0.0524, -0.0880],
         [ 0.9069,  0.1240, -0.5695,  ...,  0.0775, -0.7602, -0.2034]]],
       grad_fn=<NativeLayerNormBackward0>), hidden_states=None, attentions=None)

In [3]:
model

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Li

In [4]:
output.last_hidden_state.shape

torch.Size([1, 6, 768])

In [ ]:
encoded_input

{'input_ids': tensor([[ 101, 2070, 3793, 2005, 2944,  102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}

**Auto Classes**

In [5]:
from transformers import AutoTokenizer, AutoModel
model = AutoModel.from_pretrained("distilbert-base-uncased")
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
text = "some text for model"
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
output

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.bias', 'vocab_projector.bias', 'vocab_layer_norm.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BaseModelOutput(last_hidden_state=tensor([[[-0.3349, -0.1658, -0.0110,  ..., -0.2789,  0.0950,  0.4630],
         [-0.0397, -0.0176, -0.3552,  ..., -0.2689,  0.1300,  0.5941],
         [-0.0757,  0.3424,  0.0660,  ..., -0.5298, -0.2513,  0.1726],
         [ 0.0395, -0.0122,  0.2089,  ..., -0.3721,  0.1763,  0.1254],
         [-0.2027, -0.2934, -0.1556,  ..., -0.5440, -0.0524, -0.0880],
         [ 0.9069,  0.1240, -0.5695,  ...,  0.0775, -0.7602, -0.2034]]],
       grad_fn=<NativeLayerNormBackward0>), hidden_states=None, attentions=None)

**Classification Head**

In [6]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment")

model = AutoModelForSequenceClassification.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment")

In [7]:
model

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
             

In [8]:
text = "I enjoyed movie"
text = "Movie was waste of time"
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
output

SequenceClassifierOutput(loss=None, logits=tensor([[ 2.9619, -0.3124, -2.6414]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

**Post Processing**

In [9]:
import numpy as np
logits = output.logits.detach().numpy()
y_pred = np.argmax(logits)
y_pred

0

In [10]:
# Normalize score
print(output.logits.softmax(dim=-1).tolist())

[[0.960126519203186, 0.03633476421236992, 0.0035387128591537476]]


**Prediction on GPU**

In [11]:
model = model.to('cuda')
text = "I enjoyed movie"
# text = "Movie was waste of time"
encoded_input = tokenizer(text, return_tensors='pt').to('cuda')
output = model(**encoded_input)
logits = output.logits.detach().cpu().numpy()
print(logits)
y_pred = np.argmax(logits)
y_pred

[[-2.3957672  -0.23097074  3.1936429 ]]


2

**Predicting Multiple Examples**

In [12]:
model = model.to('cuda')
examples = ["I enjoyed movie","Movie was waste of time"]
encoded_input = tokenizer(examples, return_tensors='pt',padding=True,truncation=True).to('cuda')
output = model(**encoded_input)
logits = output.logits.detach().cpu().numpy()
print(logits)

y_pred = np.argmax(logits,axis=-1)
y_pred

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


[[-2.3957672 -0.2309703  3.1936426]
 [ 2.961924  -0.312366  -2.6413774]]


array([2, 0])

In [ ]:
# https://www.sharpsightlabs.com/blog/numpy-argmax/